[package]
name = "elegant-paper-typst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Xyber Nova <xyber-nova@outlook.com>"]
license = "LGPL-2.1"
description = "A Typst template for elegant papers."
categories = ["paper"]
homepage = "https://github.com/ctypst/elegant-paper-typst"
repository = "https://github.com/ctypst/elegant-paper-typst"
keywords = ["typst", "template", "paper", "elegant", "cjk", "中文"]
exclude = ["*.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"